### ISSUE TITLE
Configure `docker-machine` executable

### ISSUE THREAD

**Issue by noseglid** [lawrence0819/nodedm#1]
Thanks for a cool package.

An application I develop is sometimes started from an environment where `/usr/local/bin` has not been added to the path. Since this is where `docker-machine` executable resides, this plugin doesn't work.

I'd like to see a way to configure where the executable is if it is not in a location specified by `PATH`.

**Comment by lawrence0819** [comment]
Set the path of `docker-machine` is currently not supported. I will create the new function for set path of docker-machine.

Thanks for advice.

**Comment by noseglid** [comment]
Awesome! :+1:

**Comment by noseglid** [comment]
It looks like this is not enough. It appears to really have to be in the PATH since it uses other stuff (such as drivers) from there too:
```
-> % PATH=/usr/bin:/bin:/usr/sbin:/sbin /usr/local/bin/docker-machine ls
error getting state for host default: Driver "virtualbox" not found. Do you have the plugin binary accessible in your PATH?
error getting URL for host default: Driver "virtualbox" not found. Do you have the plugin binary accessible in your PATH?
NAME      ACTIVE   DRIVER      STATE   URL   SWARM
default   -        not-found   Error
```

Would it be possible to also add a configuration which can be passed to `exec` ? Preferrably just pass along the `options` object to as the second argument to `child_process.exec`

https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by lawrence0819** [comment]
Good idea. How about add reserved keyword to existing `options` object for pass it to `exec`?

For example:
```
dm.ls({
  cmd: {
    env: {
      PATH: '/home/abc'
    }
  }
});
```

**Comment by noseglid** [comment]
I think it would be better suited to the constructor of `DockerMachine`, any command may or may not require the drivers.
Suggestion:
```
const dm = new DockerMachine(`docker-machine`, {
  execOptions: {
    env: { PATH: '/home/abc' }
  }
});
```

**Comment by lawrence0819** [comment]
I think your solution would be better.

**Comment by lawrence0819** [comment]
The unit test passed on Windows 10.

I will publish package to NPM if you tested OK.

**Comment by noseglid** [comment]
Yes, now everything works as expected! Great! Thanks for the quick feedback!

**Comment by LCTL** [comment]
Version 0.2.2 already published.
